# List
In Python programming, a list is created by placing all the items (elements) inside a square bracket [ ], separated by commas.
It can have any number of items and they may be of different types (integer, float, string etc.).

In [20]:
my_list = ['p','r','o','b','e']
print(my_list[0])  # Output: p

print(my_list[4])  # Output: e

# Error! Only integer can be used for indexing
# my_list[4.0]

p
e


In [21]:
# Nested List indexing
n_list = ["Happy", [2,0,1,5]]

print(n_list[0][1])  # Output: a

print(n_list[1][3])  # Output: 5

a
5


In [22]:
# Negative Indexing
my_list = ['p','r','o','b','e']

print(my_list[-1])  # Output: e

print(my_list[-5])  # Output: p

e
p


In [23]:
my_list = ['p','r','o','g','r','a','m','i','z']

print(my_list[2:5])  # elements 3rd to 5th

print(my_list[:-5])  # elements beginning to 4th

print(my_list[5:])   # elements 6th to end

print(my_list[:])    # elements beginning to end

['o', 'g', 'r']
['p', 'r', 'o', 'g']
['a', 'm', 'i', 'z']
['p', 'r', 'o', 'g', 'r', 'a', 'm', 'i', 'z']


In [24]:
odd = [2, 4, 6, 8]

# change the 1st item    
odd[0] = 1            
print(odd)  # Output: [1, 4, 6, 8]

# change 2nd to 4th items
odd[1:4] = [3, 5, 7]  
print(odd)  # Output: [1, 3, 5, 7]               

[1, 4, 6, 8]
[1, 3, 5, 7]


In [25]:
odd = [1, 3, 5]

odd.append(7)
print(odd)    # Output: [1, 3, 5, 7]

odd.extend([9, 11, 13])
print(odd)    # Output: [1, 3, 5, 7, 9, 11, 13]

[1, 3, 5, 7]
[1, 3, 5, 7, 9, 11, 13]


In [26]:
odd = [1, 3, 5]

print(odd + [9, 7, 5])   # Output: [1, 3, 5, 9, 7, 5]
print(["re"] * 3)        #Output: ["re", "re", "re"]

[1, 3, 5, 9, 7, 5]
['re', 're', 're']


In [27]:
odd = [1, 9]

odd.insert(1,3)
print(odd)    # Output: [1, 3, 9] 

odd[2:2] = [5, 7]
print(odd)    # Output: [1, 3, 5, 7, 9]

[1, 3, 9]
[1, 3, 5, 7, 9]


In [28]:
my_list = ['p','r','o','b','l','e','m']
my_list.remove('p')

print(my_list)    # Output: ['r', 'o', 'b', 'l', 'e', 'm']

print(my_list.pop(1))   # Output: 'o'

print(my_list)  # Output: ['r', 'b', 'l', 'e', 'm']

print(my_list.pop())  # Output: 'm'

print(my_list)  # Output: ['r', 'b', 'l', 'e']

my_list.clear()
print(my_list)  # Output: []

['r', 'o', 'b', 'l', 'e', 'm']
o
['r', 'b', 'l', 'e', 'm']
m
['r', 'b', 'l', 'e']
[]


## Python List Methods

    append() - Add an element to the end of the list
    extend() - Add all elements of a list to the another list
    insert() - Insert an item at the defined index
    remove() - Removes an item from the list
    pop() - Removes and returns an element at the given index
    clear() - Removes all items from the list
    index() - Returns the index of the first matched item
    count() - Returns the count of number of items passed as an argument
    sort() - Sort items in a list in ascending order
    reverse() - Reverse the order of items in the list
    copy() - Returns a shallow copy of the list

In [17]:
my_list = [3, 8, 1, 6, 0, 8, 4]

# Output: 1
print(my_list.index(8))

# Output: 2
print(my_list.count(8))

my_list.sort()

# Output: [0, 1, 3, 4, 6, 8, 8]
print(my_list)

my_list.reverse()

# Output: [8, 8, 6, 4, 3, 1, 0]
print(my_list)

1
2
[0, 1, 3, 4, 6, 8, 8]
[8, 8, 6, 4, 3, 1, 0]


## List Comprehension: Elegant way to create new List

List comprehension is an elegant and concise way to create new list from an existing list in Python.

In [18]:
pow2 = [2 ** x for x in range(10)]

# Output: [1, 2, 4, 8, 16, 32, 64, 128, 256, 512]
print(pow2)

[1, 2, 4, 8, 16, 32, 64, 128, 256, 512]


In [19]:
odd = [x for x in range(20) if x % 2 == 1]
odd
# [1, 3, 5, 7, 9, 11, 13, 15, 17, 19]

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]

## Build-in functions with the list

    Function	Description
    all()	    Return True if all elements of the list are true (or if the list is empty).
    any()	    Return True if any element of the list is true. If the list is empty, return False.
    enumerate()	Return an enumerate object. It contains the index and value of all the items of list as a tuple.
    len()	    Return the length (the number of items) in the list.
    list()	    Convert an iterable (tuple, string, set, dictionary) to a list.
    max()	    Return the largest item in the list.
    min()	    Return the smallest item in the list
    sorted()	Return a new sorted list (does not sort the list itself).
    sum()	    Return the sum of all elements in the list.

# NumPy Array

NumPy is a package for scientific computing which has support for a powerful N-dimensional array object. 

In [29]:
import numpy as np

zeors_array = np.zeros( (2, 3) )
print(zeors_array)

[[ 0.  0.  0.]
 [ 0.  0.  0.]]


In [31]:
A = np.arange(4)
print('A =', A)

B = np.arange(12).reshape(2, 6)
print('B =', B)


A = [0 1 2 3]
B = [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [33]:
A = np.array([[2, 4], [5, -6]])
B = np.array([[9, -3], [3, 6]])
print(A)
print(B)
C = A + B      # element wise addition
print(C)

[[ 2  4]
 [ 5 -6]]
[[ 9 -3]
 [ 3  6]]
[[11  1]
 [ 8  0]]


In [35]:
C = A.dot(B)
print(C)

[[ 30  18]
 [ 27 -51]]


In [36]:
A = np.array([[1, 4, 5, 12], 
    [-5, 8, 9, 0],
    [-6, 7, 11, 19]])

print("A[0] =", A[0]) # First Row
print("A[2] =", A[2]) # Third Row
print("A[-1] =", A[-1]) # Last Row (3rd row in this case)

A[0] = [ 1  4  5 12]
A[2] = [-6  7 11 19]
A[-1] = [-6  7 11 19]


In [37]:
A = np.array([[1, 4, 5, 12], 
    [-5, 8, 9, 0],
    [-6, 7, 11, 19]])

print("A[:,0] =",A[:,0]) # First Column
print("A[:,3] =", A[:,3]) # Fourth Column
print("A[:,-1] =", A[:,-1]) # Last Column (4th column in this case)

A[:,0] = [ 1 -5 -6]
A[:,3] = [12  0 19]
A[:,-1] = [12  0 19]


In [40]:
letters = np.array([1, 3, 5, 7, 9, 7, 5])

# 3rd to 5th elements
print(letters[2:5])        # Output: [5, 7, 9]

# 1st to 4th elements
print(letters[:-5])        # Output: [1, 3]   

# 6th to last elements
print(letters[5:])         # Output:[7, 5]

# 1st to last elements
print(letters[:])          # Output:[1, 3, 5, 7, 9, 7, 5]

# reversing a list
print(letters[::-1])          # Output:[5, 7, 9, 7, 5, 3, 1]

[5 7 9]
[1 3]
[7 5]
[1 3 5 7 9 7 5]
[5 7 9 7 5 3 1]


In [39]:
A = np.array([[1, 4, 5, 12, 14], 
    [-5, 8, 9, 0, 17],
    [-6, 7, 11, 19, 21]])

print(A[:2, :4])  # two rows, four columns

print(A[:1,])  # first row, all columns

print(A[:,2])  # all rows, second column

print(A[:, 2:5])  # all rows, third to fifth column

[[ 1  4  5 12]
 [-5  8  9  0]]
[[ 1  4  5 12 14]]
[ 5  9 11]
[[ 5 12 14]
 [ 9  0 17]
 [11 19 21]]


In [88]:
def getSpreadsheetNotation(n):
    m,remainder1 = divmod(n,703)
    row = m+1

    column = ""
    while n > 0:
        n, remainder = divmod(n - 1, 26)
        column = chr(65 + remainder) + column
        if len(column) ==3: column= column[-1:]
    
    output = str(row)+column
    return output

In [89]:
getSpreadsheetNotation(1431)

'3A'

In [9]:
def convertToTitle(num):
    title = ''
    alist = string.uppercase
    while num:
        mod = (num-1) % 26
        num = int((num - mod) / 26)  
        title += alist[mod]
    return title[::-1]

In [10]:
convertToTitle(703)

NameError: name 'string' is not defined

In [56]:
divmod(27-1,26)

(1, 0)

In [69]:
divmod(704-1,26)

(27, 1)

In [57]:
chr(65 +0)

'A'

In [63]:
divmod(1405,702)

(2, 1)

In [52]:
def rollTheString(s, roll):
    increment = [0] * len(s)
    a_to_z = [chr(i) for i in range(97, 97 + 26)]
    for num in roll:
        for i in range(num):
            increment[i] += 1
    result = ""
    for i in range(len(s)):
        index = ord(s[i]) + increment[i] - 97
        index = index % 26
        result += a_to_z[index]

    return result

In [53]:
newString = rollTheString("abz", [2,1,2])
print (newString)

ddz


In [ ]:
def getSpreadsheetNotation(n):
    m,_ = divmod(n,703)
    row = m+1

    column = ""
    if row == 1:
        while n > 0:
            n, remainder = divmod(n - 1, 26)
            column = chr(65 + remainder) + column
    else:
        _, n_remainder = divmod(n,702)
        print(n_remainder)
        while n_remainder > 0:
            n_remainder, remainder = divmod(n - 1, 26)
            column = chr(65 + remainder) + column
    
    output = str(row) + column
    return output

In [ ]:
getSpreadsheetNotation(27)

In [ ]:
getSpreadsheetNotation(1431)

In [95]:
divmod(703,26)

(27, 1)